version: '2'

networks:
  prodnetwork:
    driver: bridge

volumes:
  ci-tool-stack_jenkins:
    driver: local
  ci-tool-stack_postgres:
    driver: local
  ci-tool-stack_gitlab_config:
    driver: local
  ci-tool-stack_gitlab_logs:
    driver: local
  ci-tool-stack_gitlab_data:
    driver: local

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-tool-stack_jenkins:/var/lib/jenkins/
  depends_on:
    - nexus
    - gitlab
    - sonar
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "15432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - ci-tool-stack_postgres:/var/lib/postgresql/data

 gitlab:
  image: gitlab/gitlab-ce:8.14.4-ce.0
  restart: always
  networks:
    - prodnetwork
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - "17080:80"
    - "17443:443"
    - "12222:22"
  volumes:
    - ci-tool-stack_gitlab_config:/etc/gitlab
    - ci-tool-stack_gitlab_logs:/var/log/gitlab
    - ci-tool-stack_gitlab_data:/var/opt/gitlab
