version: '2'

networks:
  prodnetwork:
    driver: bridge

volumes:
  ci-tool-stack_jenkins:
    driver: local
  ci-tool-stack_nexus:
    driver: local
  ci-tool-stack_gitbucket:
    driver: local
#  ci-tool-stack_postgres:
#    driver: local

services:

# https://github.com/sonatype/docker-nexus3
# https://hub.docker.com/r/sonatype/nexus3/
 nexus:
  image: sonatype/nexus3
  ports:
    - "18081:8081"
  environment:
    - JAVA_MIN_MEM=256m
    - JAVA_MAX_MEM=1200m
  volumes:
    - ci-tool-stack_nexus:/nexus-data
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ci-tool-stack_jenkins:/var/lib/jenkins/
  depends_on:
    - nexus
    - gitbucket
#    - sonar
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

# sonar:
#  build: ./sonar
#  ports:
#   - "19000:9000"
#   - "15432:5432"
#  networks:
#    - prodnetwork
#  depends_on:
#    - sonardb
#  environment:
#   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
#   - SONARQUBE_JDBC_USERNAME=sonar
#   - SONARQUBE_JDBC_PASSWORD=sonar
# sonardb:
#  networks:
#    - prodnetwork
#  image: postgres
#  environment:
#   - POSTGRES_USER=sonar
#   - POSTGRES_PASSWORD=sonar
#  volumes:
#    - ci-tool-stack_postgres:/var/lib/postgresql/data

# https://github.com/f99aq8ove/docker-gitbucket
# https://hub.docker.com/r/f99aq8ove/gitbucket/
 gitbucket:
  image: f99aq8ove/gitbucket:latest
  restart: always
  networks:
    - prodnetwork
  ports:
    - "17080:8080"
    - "17222:29418"
  volumes:
    - ci-tool-stack_gitbucket:/gitbucket
